/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elsham.palace;

import ae.java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.ImageIcon;

 
  
public class dress_detals extends javax.swing.JFrame {

     Connection conn=null;
    ResultSet re=null;
    PreparedStatement str=null;
    show_new_detals show = new show_new_detals();
    int index ;
    public dress_detals() {
        initComponents();
       
        
        
         setResizable(false);
        show_bill_table();
        
        num.setEnabled(false);
            select.setEnabled(false);
    }
    
     void show_bill_table()  // بعرض كل الفساتين اللى ف السيستم
    {
        conn = Java_connect.connect();
        try{
            String sql ="select id , type , date from new_dress_table";
            str = conn.prepareStatement(sql);
            re =str.executeQuery();
            dress_table.setModel(DbUtils.resultSetToTableModel(re));
            
            conn.close();
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dress_table = new javax.swing.JTable();
        txt_select = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        num = new javax.swing.JTextField();
        select = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("رجوع");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dress_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dress_table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dress_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dress_table.setAlignmentX(2.0F);
        dress_table.setAlignmentY(2.0F);
        dress_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dress_table.setRowHeight(50);
        dress_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dress_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dress_table);

        txt_select.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "بحث", "رقم الفستان ونوعه", "النوع فقط" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        num.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        select.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "فرح", "سواريه", "سواريه قصير", "اطفال", "خطوبه" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("بحث");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(190, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(select, 0, 167, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_select, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_select)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(select))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dress_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dress_tableMouseClicked
       
        
        
         int i =dress_table.getSelectedRow();
      
        TableModel model = dress_table.getModel();
        String ss = model.getValueAt(i, 0).toString()  ;
        String mm = model.getValueAt(i, 1).toString();
        int id = Integer.parseInt(ss);
        
        try{
             conn = Java_connect.connect();
            String sql ="select * from new_dress_table where id =? and type =? ";
            str = conn.prepareStatement(sql);
            
            str.setInt(1, id);
            str.setString(2, mm);
            
            re =str.executeQuery();
            if(re.next())
            {
                int d_id = re.getInt("id");
                String d_id_text = Integer.toString(d_id);
                show.id_d=d_id;
                
                
                String d_type = re.getString("type");
                show.ty = d_type;
                
                float d_price = re.getFloat("price");
                String d_price_text = Float.toString(d_price);
                
                String dat = re.getString("date");
               
                byte[] d_ima = re.getBytes("image");
                format = new ImageIcon(d_ima);
                
                int num = re.getInt("num_bill");
                
                
                show.setVisible(true);
                show.pack();
                show.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                 
                show.txt_id.setText(d_id_text);
              
                show.txt_image.setIcon(format);
                show.txt_type.setText(d_type);
                show.txt_price.setText(d_price_text);
                show.txt_date.setText(dat);
                show.nn.setText(Integer.toString(num));
              //  show.txt_image.setText(d_ima);
                ///////////////////////////////////////////////
                
                 
       
        String zz ="select date_today , paid from bill_table where dress_id =? and dress_type =?";
            str = conn.prepareStatement(zz);
            
            str.setString(1,d_id_text);
            str.setString(2, d_type);
            re =str.executeQuery();
             
             show.new_dress.setModel(DbUtils.resultSetToTableModel(re));
            
            }
            
            conn.close();
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       
        
        
    }//GEN-LAST:event_dress_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
user_interface u = new user_interface();
        u.setSize(1100, 1000);
        u.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String search_txt = txt_select.getSelectedItem().toString();
        
        if(search_txt == "رقم الفستان ونوعه")
        {
         num.setEnabled(true);
            select.setEnabled(true);   
            index =0;
        }
        else if(search_txt =="النوع فقط")
        {
            num.setEnabled(false);
            select.setEnabled(true); 
            index =1;
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        if(index == 0)
        {
          
            
             try{
            conn = Java_connect.connect();
            String sql ="select id , type , date from new_dress_table where id =? and type =?";
            str = conn.prepareStatement(sql);
             str.setString(1, num.getText().toString());
       str.setString(2,select.getSelectedItem().toString());
            re =str.executeQuery();
            dress_table.setModel(DbUtils.resultSetToTableModel(re));
            
            conn.close();
            
        }catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            }  
        }
        
        else if(index == 1)
        {
             try{
            conn = Java_connect.connect();
            String sql ="select id , type , date from new_dress_table where type =?";
            str = conn.prepareStatement(sql);
           //  str.setString(1, num.getText().toString());
       str.setString(1,select.getSelectedItem().toString());
            re =str.executeQuery();
            dress_table.setModel(DbUtils.resultSetToTableModel(re));
            
            conn.close();
            
        }catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            }  
            
            
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dress_detals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dress_detals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dress_detals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dress_detals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dress_detals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dress_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox select;
    private javax.swing.JComboBox txt_select;
    // End of variables declaration//GEN-END:variables


private ImageIcon format =null;
}
