/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package elsham.palace;

import ae.java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.ByteArrayOutputStream;
public class new_adresss extends javax.swing.JFrame {
    
    Connection conn=null;
    ResultSet re=null;
    PreparedStatement str=null;
   

    
    public new_adresss() {
        
        initComponents();
       
        
        
         setResizable(false);
      
          show_date();
          show_image();
    }

    
    void show_image()
    {
        file_name = "F:\\elsham palace\\3.jpg.jpg";
        //file_name = "F:\\elsham palace\\3.jpg";
        
        // txt.setText(file_name);
        //  ImageIcon im = new ImageIcon(new ImageIcon(file_name).getImage().getScaledInstance(image_txt.getWidth(), image_txt.getHeight(), ))
         
         try{
             File image = new File(file_name);
             FileInputStream fls = new FileInputStream(image);
             ByteArrayOutputStream bos = new ByteArrayOutputStream();
             byte[] buf =new byte[1024];
             for(int rn ; (rn = fls.read(buf))!=-1 ; )
             {
                 bos.write(buf,0,rn);
             }
             
             d_image = bos.toByteArray();
         }catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
       
        
    }
    
   void show_date()
   {
       Date d =new Date();
       SimpleDateFormat s =new SimpleDateFormat("dd-MM-yyyy");
       txt_date.setText(s.format(d));
      
   }
    
   
   String re_date()
   {
       Date d =new Date();
       SimpleDateFormat s =new SimpleDateFormat("dd-MM-yyyy");
       return s.format(d);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        id_dress = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        type_dress = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        price_dress = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 102));
        jButton2.setText("حفظ البيانات");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        id_dress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane4.setViewportView(id_dress);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("السعر ");

        type_dress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        type_dress.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "فرح", "سواريه", "سواريه قصير", "اطفال", "خطوبه" }));
        type_dress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_dressActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("تحميل صوره");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("رقم الفستان");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("تاريخ الشراء ");

        price_dress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(price_dress);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("نوع الفستان");

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("رجوع");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type_dress, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_dress, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void type_dressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_dressActionPerformed
     
        
    }//GEN-LAST:event_type_dressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser choos = new JFileChooser();
        choos.showOpenDialog(null);
        File f =choos.getSelectedFile();
         file_name = f.getAbsolutePath();
         
       
        
        //  ImageIcon im = new ImageIcon(new ImageIcon(file_name).getImage().getScaledInstance(image_txt.getWidth(), image_txt.getHeight(), ))
         
         try{
             File image = new File(file_name);
             FileInputStream fls = new FileInputStream(image);
             ByteArrayOutputStream bos = new ByteArrayOutputStream();
             byte[] buf =new byte[1024];
             for(int rn ; (rn = fls.read(buf))!=-1 ; )
             {
                 bos.write(buf,0,rn);
             }
             
             d_image = bos.toByteArray();
         }catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
       
        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void insert_new_dress()
    {
            try
            {
                  conn = Java_connect.connect();

                String m = "Insert into new_dress_table (id,type,price,date,image,num_bill) values(?,?,?,?,?,?)";

                 str = conn.prepareStatement(m);
                // String data =data_dress.getDate().toString();
                 String da = re_date();
               str.setString(1, id_dress.getText());
               str.setString(2, type_dress.getSelectedItem().toString());
               str.setString(3, price_dress.getText());
               str.setString(4, da );
               str.setBytes(5, d_image);
               str.setInt(6, 0);
                str.execute();

               // JOptionPane.showMessageDialog(null, "تم حفظ البانات");
                conn.close();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
    
    
    }
    
    
    public void insert_show_money( String da , String dat ,String mony)
    {
        try {
              conn = Java_connect.connect();
          //  String daa = re_date();
           // String dat = " تم شراء فستان نوعه "+type_dress.getSelectedItem().toString()+" بسعر " + price_dress.getText();
            String sql = "insert into loss_table (date,data,mony_less) values(?,?,?)";
            
          //  String ss = "تم شراء فستان نوعه "+type_dress.getSelectedItem().toString()+" بسعر 50 جنيه";
            str = conn.prepareStatement(sql);
            
            str.setString(1, da);
            str.setString(2, dat);
            str.setString(3, mony);
            
            str.execute();
            JOptionPane.showMessageDialog(null, "تم حفظ البيانات");
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(new_adresss.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
  
       
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        if(id_dress.getText().equals("")  || price_dress.getText().equals("") )
        {
             JOptionPane.showMessageDialog(null, "ادخل جميع البيانات");
        }
        else
        {
        insert_new_dress(); 
      String d = re_date();
      String de =   " تم شراء فستان نوعه "+type_dress.getSelectedItem().toString()+" بسعر " + price_dress.getText();
      insert_show_money(d, de,price_dress.getText());
       
       
        user_interface u = new user_interface();
        u.setSize(1100, 1000);
        u.setVisible(true);
        this.setVisible(false);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        user_interface u = new user_interface();
        u.setSize(1100, 1000);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_adresss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_adresss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_adresss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_adresss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_adresss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane id_dress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane price_dress;
    private javax.swing.JLabel txt_date;
    private javax.swing.JComboBox type_dress;
    // End of variables declaration//GEN-END:variables

String file_name =null;
int s =0;
byte[] d_image = null;


}
